Library1/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library1.Models;

namespace Library1.Controllers
{
    public class BooksController : Controller
    {
        private LibraryDb db = new LibraryDb();

        // GET: Books
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ISBN,Name,Author,Genre,Image,OnLoan")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ISBN,Name,Author,Genre,Image,OnLoan")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //count the number of loans/member
            var numLoans = from xxx in db.Loans

                           where xxx.ISBN == id
                           select xxx;

            int numberOfLoans = numLoans.Count();

            if (numberOfLoans == 0)
            {
                Book books = db.Books.Find(id);
                db.Books.Remove(books);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("DeleteBook");
            }

 }


        //Book book = db.Books.Find(id);
        //db.Books.Remove(book);
        //db.SaveChanges();
        //return RedirectToAction("Index");

        public ActionResult DeleteBook()
        {
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult Return(int? id)

        {

            var loanQuery = from item in db.Loans

                            where item.ISBN == id

                            select item;


            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Loan bookTable = db.Loans.Find(id);

            if (bookTable == null)

            {

                return HttpNotFound();

            }



            return View(bookTable);
        }



        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult ReturnBook(int id)

        {

            var loanQuery = from item in db.Loans

                            where item.ISBN == id

                            select item;



            if (ModelState.IsValid)

            {

                var book = db.Loans.FirstOrDefault(s => s.ISBN == id);

                if (book != null)

                {
                    book.Book.OnLoan = 0;
                    //book.FinePrice=
                    db.Entry(book).State = EntityState.Modified;

                    db.SaveChanges();
                    return RedirectToAction("Index");

                }

            }



            return View();

        }


        public ActionResult QuickSearch(string term)
        {
            var books = GetBooks(term).Select(a => new { value = a.Name });
            return Json(books, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BookSearch(string qb)
        {
            var books = GetBooks(qb);

            return PartialView(books);


        }
        private List<Book> GetBooks(string searchString)
        {
            return db.Books
                .Where(a => a.Name.Contains(searchString))
                .ToList();
        }



        
    }
}

Library1/Controllers/CheckoutController.cs
using Library1.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library1.Controllers
{
    public class CheckoutController : Controller
    {
        // GET: Checkout
        public LibraryDb db = new LibraryDb();

        // GET: Checkout
        public ActionResult Index()

        {

            return View();
        }

        [HttpGet]
        public ActionResult Checkout()

        {


            //  int? MemberId, string name
            //get member's names for drop down list

            // var MemberList = new List<string>();


            // var checkoutdate = db.Loans.Include(g => g.Book.Name);

            var MemberQuery = from item in db.Members

                              select item;

            var AvailableBooks = from item in db.Books.Where(g => g.OnLoan == 0)
                                 select item;


            

            //var AvailableBooks = from item in db.Loans.Where(a => a.ReturnDate > DateTime.Now)
            //                    select item;

            //populate view model to allow data from different tables to be used in same view

            var model = new CheckoutVM

            {

                Member = MemberQuery.Select(a => new SelectListItem

                {

                    Text = a.Name,

                    Value = a.Name

                }),

                Book = AvailableBooks.Select(a => new SelectListItem
                {
                    Text = a.Name,

                    Value = a.Name
                }
                ),

                CheckoutDate = DateTime.Now,

                ReturnDate = DateTime.Now.AddDays(14),



            };



            return View(model);

        }

        [HttpPost]
        public ActionResult CheckoutResult(CheckoutVM model)

        {
            //get member's names for drop down list

            var MemberList = new List<string>();

            var MemberQuery = from item in db.Members

                              select item;

            var AvailableBooks = from item in db.Books.Where(g => g.OnLoan == 0)
                                 select item;


            //populate view model

            var model1 = new CheckoutVM

            {

                Member = MemberQuery.Select(a => new SelectListItem

                {

                    Text = a.Name,

                    Value = a.MemberId.ToString()

                }),

                Book = AvailableBooks.Select(a => new SelectListItem

                {

                    Text = a.Name,

                    Value = a.ISBN.ToString()

                }),

                CheckoutDate = DateTime.Now,

                ReturnDate = DateTime.Now.AddDays(14),



            };

            if (ModelState.IsValid)

            {
                var CheckoutDate = model.CheckoutDate;
                // AvailableBooks. = model.CheckoutDate; create an entity of what you want.....change var to  viewbag....
                var ReturnDate = model.ReturnDate;

                //used to get the instance of the member where the name == name in vm

                var result = db.Members.FirstOrDefault(s => s.Name == model.MemberName);

                //takes the book from the database that is being looked at

                var bookLoan = db.Books.FirstOrDefault(s => s.Name == model.BookTitle);

                var loanID = model.LoanId + 1;


                //Loan table represents the book checked out by selected  member (loan=book and member)

                if (bookLoan != null)

                {

                    bookLoan.OnLoan = 1;

                    Loan loan = new Loan
                    {
                        LoanId = loanID,
                        MemberId = result.MemberId,
                        ISBN = bookLoan.ISBN,
                        ReturnDate = ReturnDate,
                        CheckOutDate = CheckoutDate,
                        FinePrice = 0,


                    };
                    db.Loans.Add(loan);

                    //bookLoan.OnLoan = 1;

                    db.Entry(bookLoan).State = EntityState.Modified;
                    //db.Entry(loan).State = EntityState.Modified;
                    db.SaveChanges();

                }



            }
            return View();


        }

    }

}
   

Library1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Library1/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library1.Models;

namespace Library1.Controllers
{
    public class MembersController : Controller
    {
        private LibraryDb db = new LibraryDb();

        // GET: Members
        public ActionResult Index()
        {
            return View(db.Members.ToList());
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemberId,Name,Address,PostCode,TelNo")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MemberId,Name,Address,PostCode,TelNo")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //count the number of loans/member
            var numLoans = from xxx in db.Loans

                           where xxx.MemberId == id
                           select xxx;

            int numberOfLoans = numLoans.Count();

            if (numberOfLoans == 0)
            {
                Member member = db.Members.Find(id);
                db.Members.Remove(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("DeleteMember");
            }
            
        }

        public ActionResult DeleteMember()
        {
            return View();
        }
        //[HttpPost]
        //public ActionResult DeleteMember(int id)

        //{

        //    //select all members
        //    //var members = db.Members.ToList();


        //    //selects members were they have no loan
        //    //get the member using their id
        //    //Member member = db.Members.Find(id);

        //    //count the number of loans/member
        //    var numLoans = from xxx in db.Loans
                           
        //                   where xxx.MemberId == id
        //                   select xxx;

        //    int numberOfLoans = numLoans.Count();

        //    if (numberOfLoans == 0)
        //    {
        //        return RedirectToAction("Delete", new { id = id });
        //    }
        //    else
        //    {
        //        return RedirectToAction("DeleteMember");
        //    }






        //   // return View();
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult QuickSearch(string term)
        {
            var members = GetMembers(term).Select(a => new { value = a.Name });

            return Json(members, JsonRequestBehavior.AllowGet);
        }


        public ActionResult MemberSearch(string qm)
        {
            var members = GetMembers(qm);

            return PartialView(members);


        }
        private List<Member> GetMembers(string searchString)
        {
            return db.Members
                .Where(a => a.Name.Contains(searchString) || a.Address.Contains(searchString))
                .ToList();
        }


       

        
          //  var AvailableBooks = from item in db.Books.Where(g => g.OnLoan == 0)
           //                      select item;


          

        
        //create Book History button in members detail pg
        //for each member select all the books they have rented-loan table
        //ISBN NO =CATegory filtering in the Loans table.If the isbn no is matching choose the last one and return mesage saying this
        //book is onloan else book returned
       



    }
}

Library1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Library1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Library1/Views/Home/Index.cshtml
    <link href="~/Content/Site.css" rel="stylesheet" />
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">


    <h1>Librarian’s Administrative System</h1>

</div>


<br />

<div class="col-sm-5 pull-right">
    <button class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal">



        <img src="~/Images/book-25155_1280-compressor.png" style="width:80%; height:75%" />


    </button>


    <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">
                        &times;
                    </button>
                    <h2 class="modal-title" id="myModalLabel">
                        Books
                    </h2>
                </div>
                <div class="modal-body">

                    <div class="text-center">
                        <p>@Html.ActionLink("Checkout Book", "Checkout", "Checkout", null, new { @class = "btn btn-primary btn-lg" })</p>

                        <br />
                        <p>@Html.ActionLink("Return Book", "Index", "BookReturn", null, new { @class = "btn btn-primary btn-lg" })</p>

                        
                        <br />
                        <p>@Html.ActionLink("Add Book", "Create", "Books", null, new { @class = "btn btn-primary btn-lg" })</p>

                        <br />
                        <p>@Html.ActionLink("Edit | Delete | Details Book", "Index", "Books", null, new { @class = "btn btn-primary btn-lg" })</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal">
                        Close
                    </button>

                </div>
            </div>
        </div>
    </div>

</div>




<div class="col-sm-5">
    <button class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModalMem">



        <img src="~/Images/computer-1331579_1280-compressor.png"  style="width:70%; height:75%"/>
    </button>


    <div class="modal fade" id="myModalMem" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabelMem" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">
                        &times;
                    </button>
                    <h2 class="modal-title" id="myModalLabelMem">
                        Members
                    </h2>
                </div>
                <div class="modal-body">
                    <div class="text-center">
                        <p>@Html.ActionLink("Add Member", "Create", "Members", null, new { @class = "btn btn-primary btn-lg" })</p>
                        <br />
                        <p>@Html.ActionLink("Edit | Delete | Details Member", "Index", "Members", null, new { @class = "btn btn-primary btn-lg" })</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal">
                        Close
                    </button>

                </div>
            </div>
        </div>
    </div>

</div>