Library1/Controllers/BookReturnController.cs
using Library1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Library1.Controllers
{
    public class BookReturnController : Controller
    {
        private LibraryDb db = new LibraryDb();


        //return a list of books on loan

        public ActionResult Index()
        {

            var loans = db.Loans.Where(a => a.Book.OnLoan == 1);


            return View(loans);


        }
        //Find book results-search results on book selection
        [HttpGet]
        public ActionResult LoanSearch(string q)
        {


            var loans = GetLoans(q);
            return PartialView(loans);



        }
        

        public List<Loan> GetLoans(string searchString)
        {


            // if (ModelState.IsValid)
            //  {
            var loan = db.Loans
                  .Where(a => a.Book.Name
                               .Contains(searchString) &&
                              a.Book.OnLoan == 1).ToList();



                return loan;
         //   }
            //  else
            // {
            //     ModelState.AddModelError("", "Something went wrong...");

            //   return new List<Loan> { loan };
            // }

            //create null oblect-pass null object
            //return a different view/partial view











            //error message


        }

    }
}

Library1/Controllers/RBooksController.cs
using Library1.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Library1.Controllers
{
    public class RBooksController : Controller
    {
        public LibraryDb db = new LibraryDb();
        // GET: RBooks
        public ActionResult Index()

        {
            var loans = db.Loans
                .Where(a => a.Book.OnLoan == 1);


            return View(loans);

            // return View(db.Loans.ToList());
        }

        [HttpGet]
        public ActionResult Return(int? id)

        {

            var loanQuery = from item in db.Loans

                            where item.LoanId == id
                            select item;

            


            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Loan bookTable = db.Loans.Find(id);

            if (bookTable == null)

            {

                return HttpNotFound();

            }



            return View(bookTable);
        }



        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult ReturnBook(int id, Loan loan)

        {

            var loanQuery = from item in db.Loans

                            where item.LoanId == id

                            select item;



            if (ModelState.IsValid)

            {

                var book = db.Loans.FirstOrDefault(s => s.LoanId == id);

                if (book != null)

                {
                    book.Book.OnLoan = 0;

                    //book.FinePrice = 0.00M;

                    
                    db.Entry(book).State = EntityState.Modified;
db.Loans.Remove(book);
                    db.SaveChanges();

                    

                    // return RedirectToAction("Index");
                }

            }


            return View();
            // return View("Index");

        }
    }
}

Library1/Views/BookReturn/Index.cshtml
@model IEnumerable<Library1.Models.Loan>

@{
    ViewBag.Title = "Index";
}


<div class="pull-right">
    <a href="@Url.Action("Index", "Home")">
        <i class="fa fa-home large"></i>
    </a>
</div>
<div class="panel panel-heading">

    <h1>Book Return</h1>

</div>

<div class="panel panel-default">
    <div class="panel-heading">Please enter the Title of the book</div>
    <div class="panel-body">
        @using (Ajax.BeginForm("LoanSearch", "BookReturn",
                   new AjaxOptions
                   {
                       InsertionMode = InsertionMode.Replace,
                       HttpMethod = "GET",
                       OnFailure = "searchFailed",
                       LoadingElementId = "ajax-loader",
                       UpdateTargetId = "searchresult",
                   }))
        {
            <input type="text" name="q" />
            <input type="submit" value="search" />
            <img id="ajax-loader"
                 src="@Url.Content("~/Images/ajax-loader.gif")"
            
            style = "display:none" />
        }
        <div id="searchresult"></div>

        <div id="searchFailed">
            @ViewBag.Error
        </div>
    </div>
</div>

@section scripts{


    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/App/Book.js"></script>

}

Library1/Views/BookReturn/LoanSearch.cshtml
@model IEnumerable<Library1.Models.Loan>




    <div id="searchresult">
        <div id="searchFailed">
            @using (Html.BeginForm("LoanSearchResults", "BookReturn", FormMethod.Post))
            {


                foreach (var item in Model)
                {
                    <div class="text-center">
                        <br />
                        <p>Member Name: @item.Member.Name</p>
                        <p>Book Title: @item.Book.Name</p>
                        <p>Book Author: @item.Book.Author</p>
                        <p>Checkout Date: @item.CheckOutDate</p>
                        <p>Return Date: @item.ReturnDate</p>
                        <br />


                        @{decimal i = 0.00M;}

                        @if (item.FinePrice > i)
                    {
                            <p> Please ask @item.Member.Name to pay the following fine for the @item.Book.Name book:</p>
                            <P class="label-warning">£@item.FinePrice</P>
                        }
                        else
                        {
                            <p class="label-info">No fine to pay</p>
                        }


                    </div>


                    <br />


                    <div class="col-md-12">

                        @Html.ActionLink("Return Book", "Return", "RBooks", new { id = item.LoanId }, new { @class = "btn btn-primary" })

                        <br />

                    </div>




                                }

                            }


        </div>
    </div>

    @section scripts{


        <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/Scripts/App/Book.js"></script>

        <script src="~/Scripts/App/searchFailed.js"></script>
    }